spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./database/db1;AUTO_SERVER=TRUE;
    username: sa
    password:
  jpa:
    show_sql: true
    database: h2
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false